// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Booking struct {
	ID       int32 `json:"id"`
	Sid      int32 `json:"sid"`
	Uid      int32 `json:"uid"`
	Duration int32 `json:"duration"`
	Cost     int64 `json:"cost"`
}

type Equipment struct {
	ID          int32  `json:"id"`
	Type        int32  `json:"type"`
	Seller      int32  `json:"seller"`
	Cost        int32  `json:"cost"`
	Description string `json:"description"`
	Photo       []byte `json:"photo"`
}

type Rent struct {
	ID        int32 `json:"id"`
	Equipment int32 `json:"equipment"`
	Buyer     int32 `json:"buyer"`
	Cost      int32 `json:"cost"`
}

type Seller struct {
	ID       int32  `json:"id"`
	Uid      int32  `json:"uid"`
	Location string `json:"location"`
}

type Staff struct {
	ID       int32  `json:"id"`
	Cost     int32  `json:"cost"`
	Location string `json:"location"`
	Photo    []byte `json:"photo"`
	Uid      int32  `json:"uid"`
}

type User struct {
	ID        int32        `json:"id"`
	FullName  string       `json:"full_name"`
	CreatedAt sql.NullTime `json:"created_at"`
	Mobile    int64        `json:"mobile"`
	Type      int32        `json:"type"`
}
